# Generated by Django 2.1.3 on 2018-12-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novinky', '0002_auto_20181202_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novinka',
            name='date',
        ),
        migrations.RemoveField(
            model_name='novinka',
            name='thumb',
        ),
    ]
