# Generated by Django 2.1.3 on 2018-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novinky', '0005_auto_20181202_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='novinka',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
