# Generated by Django 2.1.3 on 2018-12-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_auto_20181207_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='delka',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='hodnoceni',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rok',
            field=models.BigIntegerField(blank=True),
        ),
    ]
