# Generated by Django 2.1.3 on 2018-12-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_remove_film_nadpis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
