# Generated by Django 2.1.3 on 2018-12-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0006_auto_20181208_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
