# Generated by Django 2.1.3 on 2018-12-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0007_auto_20181208_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='delka',
        ),
        migrations.RemoveField(
            model_name='film',
            name='hodnoceni',
        ),
        migrations.RemoveField(
            model_name='film',
            name='obsah',
        ),
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rezije',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rok',
        ),
        migrations.RemoveField(
            model_name='film',
            name='scenar',
        ),
        migrations.RemoveField(
            model_name='film',
            name='zanr',
        ),
        migrations.RemoveField(
            model_name='film',
            name='zeme',
        ),
    ]
