# Generated by Django 2.1.3 on 2018-12-07 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0008_auto_20181208_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=300)),
                ('recenz', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='delka',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='hodnoceni',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='obsah',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='poster.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='film',
            name='rezije',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='film',
            name='rok',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='scenar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='film',
            name='zanr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='film',
            name='zeme',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='recenze',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='filmy.Film'),
        ),
    ]
