# Generated by Django 2.1.3 on 2018-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobnosti', '0006_remove_herec_jmeno'),
        ('filmy', '0009_auto_20181208_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='hraji',
            field=models.ManyToManyField(to='osobnosti.Herec'),
        ),
    ]
