# Generated by Django 2.1.3 on 2018-12-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osobnosti', '0006_remove_herec_jmeno'),
        ('filmy', '0011_auto_20181208_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HerecAutor',
            new_name='HerecFilm',
        ),
    ]
