# Generated by Django 2.1.3 on 2018-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0012_auto_20181208_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='hodnoceno',
            field=models.BigIntegerField(default=0),
        ),
    ]
