# Generated by Django 2.1.3 on 2018-12-08 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300)),
                ('fotografie', models.ImageField(blank=True, default='DiCaprio.png', upload_to='')),
                ('jmeno', models.CharField(blank=True, max_length=300)),
                ('narozeniny', models.DateTimeField(default=datetime.date.today)),
                ('misto_narozeni', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
