# Generated by Django 2.1.3 on 2018-12-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobnosti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herec',
            name='ziv',
            field=models.TextField(blank=True),
        ),
    ]
