# Generated by Django 2.1.3 on 2018-12-08 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osobnosti', '0002_herec_ziv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herec',
            name='narozeniny',
            field=models.DateTimeField(default=datetime.date(2018, 12, 8)),
        ),
    ]
