# Generated by Django 2.1.3 on 2018-12-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osobnosti', '0005_auto_20181208_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herec',
            name='jmeno',
        ),
    ]
